"""init

Revision ID: dc1001135c6d
Revises: 690976affbfc
Create Date: 2024-04-14 07:34:38.588837

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "dc1001135c6d"
down_revision = "690976affbfc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("payment", sa.Column("user_id", sa.UUID(), nullable=False))
    op.create_foreign_key(
        None, "payment", "user_account", ["user_id"], ["user_id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "payment", type_="foreignkey")
    op.drop_column("payment", "user_id")
    # ### end Alembic commands ###
