"""init

Revision ID: 62242286836e
Revises: 4243aa844a97
Create Date: 2024-04-14 03:49:18.507937

"""

# revision identifiers, used by Alembic.
revision = "62242286836e"
down_revision = "4243aa844a97"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
