"""init

Revision ID: 6f1b04dd74c6
Revises: 62242286836e
Create Date: 2024-04-14 04:01:54.591002

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "6f1b04dd74c6"
down_revision = "62242286836e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "partner",
        "description",
        existing_type=sa.VARCHAR(length=512),
        type_=sa.Text(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "partner",
        "description",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=512),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
